version: "2"
services:
  db:
    image: mongo:4
  api:
    build: .
    image: mern-crud
    command: nodemon server
    ports:
      - "3000:3000"
    environment:
      # to use MongoAtlas:
      # - "DB=mongodb+srv://YOUR_DB_USERNAME:YOURPASSWORD@cluster0.wa1di.mongodb.net/mern-crud?retryWrites=true&w=majority"
      # to access via docker: docker exec -it mern-crud_db_1 mongo "mongodb+srv://cluster0.wa1di.mongodb.net/mern-crud" --username YOUR_DB_USERNAME

      # to use Docker container change db config string to db: process.env.DB:
      # - "DB=mongodb://db/mern-crud"

      - "CORS=1"
      - "DEBUG=express:*"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
  web:
    image: mern-crud
    command: npm start --prefix react-src
    ports:
      - "4200:4200"
    environment:
      - "REACT_APP_API_URL=http://localhost:3000"
    volumes:
      - ./react-src:/usr/src/app/react-src
      - /usr/src/app/react-src/node_modules
    depends_on:
      - api
